version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*bufio.Writer).Write
        - (*bufio.Writer).WriteByte
        - (*github.com/xuri/excelize/v2.File).Close
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - errcheck
